name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        go-version: 1.10.x
    - name: make
      run: |
        # export PATH=$PATH:$(go env GOPATH)/bin  # temporary fix. See https://github.com/actions/setup-go/issues/14
        mkdir -p $GOPATH/src/github.com/it-projects-llc/
        ln -s $(pwd) /home/runner/go/src/github.com/it-projects-llc/hound/
        make
    - uses: matheusalbino/git-commit@v1.0.1
      name: Commit updates
      with:
        user-name: Marc Demo (from Github Actions)
        user-email: i18n-bot@it-projects.info
        message: |
          :alien: rebuild bindata.go
          
          Sent from Github Actions (see .github/workflows/main.yml )
        github-token: ${{ secrets.GITHUB_TOKEN }}
