name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        go-version: 1.10.x
    - name: make
      run: |
        make
    - uses: matheusalbino/git-commit@v1.0.1
      name: Commit updates
      with:
        user-name: Marc Demo (from Github Actions)
        user-email: i18n-bot@it-projects.info
        message: |
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/main.yml )
        github-token: ${{ secrets.GITHUB_TOKEN }}
