name: Preview PR

on: [pull_request]

jobs:
  pr_image:

    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.number }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        go-version: 1.10.x
    - name: make
      run: |
        mkdir -p $(go env GOPATH)/src/github.com/it-projects-llc/
        ln -s $(pwd) $(go env GOPATH)/src/github.com/it-projects-llc/hound
        make
    - name: Fetch CI Image
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker pull docker.pkg.github.com/it-projects-llc/hound/ci -u $username -p $password
    - name: Build and Publish PR Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: it-projects-llc/hound/pr${PR}:${GITHUB_SHA}
        dockerfile: DockerfilePR
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Post instruction in PR
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          To test updates run:

              docker run -p 6080:6080 --rm docker.pkg.github.com/it-projects-llc/hound/pr${PR}:${GITHUB_SHA}

          You may need be authenticated:
          
              docker login docker.pkg.github.com -u GITHUB_USERNAME -p GITHUB_TOKEN 
          > Posted from Github Actions (see .github/workflows/pr.yml)
